### ISSUE TITLE
Potential reporting approaches?

### ISSUE THREAD

**Issue by dhartford** [automatictester/lightning#214]
Hi team,
Using jmeter-lightning for doing average response time and throughput checks in an aws lambda runtime from csv files passed to it. After some quick digging around, I couldn't find any pre-existing reporting approaches (to drop to a target S3 location for example).

Are there any potential quick approaches to create, to quote, 'pretty' reports from the data to publish results in a formal matter on top of the nicely done pass/fail checks used for integration into the developer pipeline.

i.e. starting with a tabular report format to pivot the discussion, not as a final target

label | 90th percentile (max limit: 200ms) | 99th percentile (max limit: 500ms) | throughput (minimum limit: 10 req/sec)
MyApploc1 | 120ms | 550ms** | 12 req/sec
MyApploc2 | 220ms** | 300ms | 30 req/sec
MyApploc3 | 100ms | 150ms | 5 req/sec**

thanks for any discussion and potential solutions.

**Comment by automatictester** [comment]
Hi there, thanks for your interest. I can confirm this is not something I have on the roadmap. Current reporting include producing [JUnit XML files](http://automatictester.github.io/lightning/ci_cd_server_integration.html) as well as [enhanced integration with TeamCity](http://automatictester.github.io/lightning/enhanced_teamcity_integration.html).
Lightning was created in order to give simple pass/fail answer rather than provide pretty reports etc. If you are interested in graphs/charts/tables etc you may want to consider tools like [Jenkins Performance Plugin](https://plugins.jenkins.io/performance) or similar, depending on the stack you're using.
