### ISSUE TITLE
Maven warnings

### ISSUE THREAD

**Issue by automatictester** [automatictester/lightning#8]
Get rid of warnings raised by `mvn clean compile assembly:single`

**Comment by automatictester** [comment]
Contributors are welcome to help with this one.

**Comment by ggeda** [comment]
I will take a look at this.

**Comment by automatictester** [comment]
Cool!

**Comment by ggeda** [comment]
This is the stated goal of this task, to remove the two warnings thrown today by 

`mvn clean compile assembly:single`

[**WARNING**] Configuration options: 'appendAssemblyId' is set to false, and 'classifier' is missing.
Instead of attaching the assembly file: \lightning\target\lightning-standalone-1.1.1-SNAPSHOT.jar, 
it will become the file for main project artifact.
NOTE: If multiple descriptors or descriptor-formats are provided for this project, the value of this file will be non-deterministic!
[**WARNING**] Replacing pre-existing project main-artifact file: \lightning\target\classes
with assembly file: c:\Users\GE011GE\myrepos\git\github\forked\lightning\lightning\target\lightning-standalone-1.1.1-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**Comment by automatictester** [comment]
How is it going? Do you think you can fix it over next few weeks?
